name: publish
on:
  push:
    branches:
      - release
permissions:
  contents: read
  packages: write
jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
      - name: Build the hello-docker Docker image
        run: |
          docker build . --tag ghcr.io/yohan744/lead-dev:production
          docker push ghcr.io/yohan744/lead-dev:production